project:
  type: website
  preview:
    port: 4200
    browser: false

website:
  title: "siddharth.tumre"
  site-url: http://siddharthtumre.github.io
  description: "Personal blog on research, insights, and applications of NLP and Large Language Models."
  navbar:
    right:
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog 
      - href: about.qmd
        text: About
      - text: More
        menu:
          - icon: file-earmark-pdf
            text: View CV (PDF)
            url: CV1104.pdf
            target: _blank
            rel: noopener
          - icon: github
            text: GitHub
            href: https://github.com/siddharthtumre
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/siddharth-tumre/
          - icon: twitter
            text: Twitter
            href: https://x.com/siddharth_tumre
          - icon: rss
            text: RSS Feed
            href: index.xml
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Siddharth Tumre."
    right:
      - icon: envelope
        href: mailto:siddharth.tumre@outlook.com
      - icon: github
        href: https://github.com/siddharthtumre
      - icon: linkedin
        href: https://www.linkedin.com/in/siddharth-tumre/
      - icon: twitter
        href: https://x.com/siddharth_tumre
format:
  html:
    smooth-scroll: true
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto

comments:
  giscus:
    repo: siddharthtumre/siddharthtumre.github.io