---
title: "Improved Near-Duplicate Detection for Aggregated and Paywalled News-Feeds"
type: "proceeding"
author: "Siddharth Tumre, Sangameshwar Patil, Alok Kumar"
year: "2025"
publication: "NAACL"
link: "https://aclanthology.org/2025.naacl-industry.73/"
pdf: "https://aclanthology.org/2025.naacl-industry.73.pdf"
toc: false
categories:
  - Near-Duplicate Detection
  - News Analytics
  - Archival Conference Papers
---

## Citation (APA)

> Tumre, S., Patil, S., & Kumar, A. (2025, April). Improved near-duplicate detection for aggregated and paywalled news-feeds. In Proceedings of the 2025 Conference of the Nations of the Americas Chapter of the Association for Computational Linguistics: Human Language Technologies (Volume 3: Industry Track) (pp. 979-987).


## Abstract

News aggregators play a key role in the rapidly evolving digital landscape by providing comprehensive and timely news stories aggregated from diverse sources into one feed. As these articles are sourced from different outlets, they often end up covering the same underlying event but differ in phrasing, formatting or supplemented with additional details. It is crucial for the news aggregators to identify these near-duplicates, improving the content quality and user engagement by steering away from redundant information. The problem of near-duplicate news detection has become harder with increasing use of paywalls by the news websites resulting in restricted access to the content. It is now common to get only the headline and a short snippet from the article. Previous works have concentrated on full length versions of documents such as webpages. There is very little work that focuses on this variation of the near-duplicate detection problem in which only headline and a small text blurb is available for each news article. We propose Near-Duplicate Detection Using Metadata Augmented Communities (NDD-MAC) approach that combines embeddings from pretrained language model (PLM) and latent metadata of a news article followed by community detection to identify clusters of near-duplicates. We show the efficacy of proposed approach using 2 different real-world datasets. By integrating metadata with community detection, NDD-MAC is able to detect nuanced similarities and differences in news snippets and offers an industrial scale solution for the near-duplicate detection in scenarios with restricted content availability.